puts "Enter number or name of month "
month = gets.chomp
if month == "January" or month == "1" 
   puts "First"
elsif month == "February" or month == "2"
   puts "First"
elsif month == "March" or month == "3"
   puts "First" 
elsif month == "April" or month == "4"
   puts "Second"
elsif month == "May" or month == "5"
   puts "Second"
elsif month == "June" or month == "6"
   puts "Second"
elsif month == "July" or month == "7"
   puts "Third"
elsif month == "August" or month == "8"
   puts "Third"
elsif month == "September" or month == "9"
   puts "Third"
elsif month == "October" or month == "10"
   puts "Fourth"
elsif month == "November" or month == "11"
   puts "Fourth"
elsif month == "December" or month == "12"
   puts "Fourth"
else 
   puts "Error, Please enter month!"
end 